    
module.exports = {
    upComingData: [
        {
            id: 1,
            salonName: 'Mane Beautilocks',
            date: 'Sat,20 Aug',
            time: '07:00 PM',
            coverImg: require('../assets/images/UpcomingImage.png'),
            pimg: require('../assets/images/PopularSalons.png'),
            salonAddress: '2/250 Cambridge St,',
            apointmentDate: 'Fri,12 Jun',
            apointmentTime: '2Pm- 3Pm',
            alocateTime: '60 min',
            serviceTitle: 'Total Services',
            serviceCount: '2',
            address: '2/250 Cambridge St, Wembley WA 6014, Australia',
            ratingText: '3.0',
            shopStatus: 'open',
            book: 'Book Now',
            review: '(21)',
            desti: "1.4 mi",
            stars: require('../assets/images/Star.png'),
            image: [
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
            ],
        },
        {
            id: 2,
            salonName: 'Beautilocks',
            date: 'Sat,20 Aug',
            time: '07:00 PM',
            coverImg: require('../assets/images/UpcomingImage.png'),
            pimg: require('../assets/images/PopularSalons.png'),
            salonAddress: '2/250 Cambridge St,',
            apointmentDate: 'Fri,12 Jun',
            apointmentTime: '2Pm- 3Pm',
            alocateTime: '60 min',
            serviceTitle: 'Total Services',
            address: '2/250 Cambridge St, Wembley WA 6014, Australia',
            serviceCount: '2',
            ratingText: '3.0',
            shopStatus: 'open',
            book: 'Book Now',
            review: '(21)',
            desti: "1.4 mi",
            stars: require('../assets/images/Star.png'),
            image: [
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
            ],
        },
        {
            id: 3,
            salonName: 'Mane Beautilocks',
            date: 'Sat,20 Aug',
            time: '07:00 PM',
            coverImg: require('../assets/images/UpcomingImage.png'),
            pimg: require('../assets/images/PopularSalons.png'),
            salonAddress: '2/250 Cambridge St,',
            apointmentDate: 'Fri,12 Jun',
            address: '2/250 Cambridge St, Wembley WA 6014, Australia',
            apointmentTime: '2Pm- 3Pm',
            alocateTime: '60 min',
            serviceTitle: 'Total Services',
            serviceCount: '2',
            ratingText: '3.0',
            shopStatus: 'open',
            book: 'Book Now',
            review: '(21)',
            desti: "1.4 mi",
            stars: require('../assets/images/Star.png'),
            image: [
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
            ],
        },
        {
            id: 4,
            salonName: 'Mane Beautilocks',
            date: 'Sat,20 Aug',
            time: '07:00 PM',
            coverImg: require('../assets/images/UpcomingImage.png'),
            pimg: require('../assets/images/PopularSalons.png'),
            salonAddress: '2/250 Cambridge St,',
            apointmentDate: 'Fri,12 Jun',
            apointmentTime: '2Pm- 3Pm',
            address: '2/250 Cambridge St, Wembley WA 6014, Australia',
            alocateTime: '60 min',
            serviceTitle: 'Total Services',
            serviceCount: '2',
            ratingText: '3.0',
            shopStatus: 'open',
            book: 'Book Now',
            review: '(21)',
            desti: "1.4 mi",
            stars: require('../assets/images/Star.png'),
            image: [
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
            ],
        },
        {
            id: 5,
            salonName: 'Mane Beautilocks',
            date: 'Sat,20 Aug',
            time: '07:00 PM',
            coverImg: require('../assets/images/UpcomingImage.png'),
            pimg: require('../assets/images/PopularSalons.png'),
            salonAddress: '2/250 Cambridge St,',
            apointmentDate: 'Fri,12 Jun',
            apointmentTime: '2Pm- 3Pm',
            address: '2/250 Cambridge St, Wembley WA 6014, Australia',
            alocateTime: '60 min',
            serviceTitle: 'Total Services',
            serviceCount: '2',
            ratingText: '3.0',
            shopStatus: 'open',
            book: 'Book Now',
            review: '(21)',
            desti: "1.4 mi",
            stars: require('../assets/images/Star.png'),
            image: [
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
            ],
        },
    ],
    exploreData: [
        {
            id: 1,
            serviceName: 'Hair Cut',
            image: require('../assets/images/Service_1.png')
        },
        {
            id: 1,
            serviceName: 'Beard',
            image: require('../assets/images/Service_2.png'),
        },
        {
            id: 1,
            serviceName: 'Facials',
            image: require('../assets/images/Service_3.png'),
        },
        {
            id: 1,
            serviceName: 'Hair Colour',
            image: require('../assets/images/Service_4.png'),
        },
        {
            id: 1,
            serviceName: 'Manicure',
            image: require('../assets/images/Service_1.png')
        },
        {
            id: 1,
            serviceName: 'Pedicure',
            image: require('../assets/images/Service_2.png'),
        },
        {
            id: 1,
            serviceName: 'Waxing',
            image: require('../assets/images/Service_3.png'),
        },
        {
            id: 1,
            serviceName: 'Threading',
            image: require('../assets/images/Service_4.png'),
        },
    ],
    popularData: [
        {
            id: 1,
            salonName: 'Mane Beautilocks',
            address: "2/250 Cambridge St",
            ratingText: '3.0',
            shopStatus: 'open',
            book: 'Book Now',
            review: '(21)',
            desti: "1.4 mi",
            image: require('../assets/images/PopularSalons.png'),
            stars: require('../assets/images/Stars.png'),

        },
        {
            id: 2,
            salonName: 'Mane Beautilocks',
            address: "2/250 Cambridge St",
            ratingText: '3.0',
            shopStatus: 'open',
            book: 'Book Now',
            review: '(21)',
            desti: "1.4 mi",
            image: require('../assets/images/PopularSalons.png'),
            stars: require('../assets/images/Stars.png'),
        },
        {
            id: 3,
            salonName: 'Mane Beautilocks',
            address: "2/250 Cambridge St",
            ratingText: '3.0',
            shopStatus: 'open',
            book: 'Book Now',
            review: '(21)',
            desti: "1.4 mi",
            image: require('../assets/images/PopularSalons.png'),
            stars: require('../assets/images/Stars.png'),
        },
        {
            id: 4,
            salonName: 'Mane Beautilocks',
            address: "2/250 Cambridge St",
            ratingText: '3.0',
            shopStatus: 'open',
            book: 'Book Now',
            review: '(21)',
            desti: "1.4 mi",
            image: require('../assets/images/PopularSalons.png'),
            stars: require('../assets/images/Stars.png'),
        },
        {
            id: 5,
            salonName: 'Mane Beautilocks',
            address: "2/250 Cambridge St",
            ratingText: '3.0',
            shopStatus: 'open',
            book: 'Book Now',
            review: '(21)',
            desti: "1.4 mi",
            image: require('../assets/images/PopularSalons.png'),
            stars: require('../assets/images/Stars.png'),
        },
        {
            id: 6,
            salonName: 'Mane Beautilocks',
            address: "2/250 Cambridge St",
            ratingText: '3.0',
            shopStatus: 'open',
            book: 'Book Now',
            review: '(21)',
            desti: "1.4 mi",
            image: require('../assets/images/PopularSalons.png'),
            stars: require('../assets/images/Stars.png'),
        },

    ],
    popularBlogData: [
        {
            id: 0,
            name: 'Javed Habib',
            dollar: '-$120.00',
            day: '15 days ago ',

            nameshop: '21 Best Hand Creams to Save Your Dry, Cracked Skin',
            date: 'Apr 14.02:30 pm ',
            info: 'Whether you want to look younger or embrace your age, these haircuts will make you....',
            image: [
                'https://source.unsplash.com/1024x768/?nature',
                'https://source.unsplash.com/1024x768/?water',
                'https://source.unsplash.com/1024x768/?girl',
                'https://source.unsplash.com/1024x768/?tree',
            ],
            coverImg: require('../assets/images/GirlOfPopularblogs.png'),
            blogImg: require('../assets/images/PopularBlogsIcon.png'),
            text: ' 7 Natural Hair Dyes: How to Color Your Hair at home',
            main: 'The Best Hair Styling Tips and Secrets from Professional Salon Stylists',
            Title: '1. Know your hair type',
            Text1:
                'Getting to know your hair can prevent you from wreaking havoc on innocent strands. So, before you pick up a heating tool or brush, learn to distinguish your hair type. Hair typically falls under two categories: Fine and thick.',
            Text2:
                'Your hair is fine if a single strand is hard to see; you struggle with maintaining volume; and locks never feel heavy. You have fewer strands, which are super skinny.',
            subImg: require('../assets/images/BlogInternalImage.png'),
            Text3:
                'Your hair is thick if it feels coarser; bobby pins can’t hold styles in place; and your biggest problem is taming frizz. You seem to have an infinite amount of strands and they weigh a ton.',
        },
        {
            id: 1,
            name: 'Javed Habib',
            dollar: '-$120.00',
            nameshop: '21 Best Hand Creams to Save Your Dry, Cracked Skin',
            date: ' Apr 14.02:30 pm ',
            day: '15 days ago ',
            info: 'debit Whether you want to look younger or embrace your age, these haircuts will make you....',
            image: [
                'https://source.unsplash.com/1024x768/?nature',
                'https://source.unsplash.com/1024x768/?water',
                'https://source.unsplash.com/1024x768/?girl',
                'https://source.unsplash.com/1024x768/?tree',
            ],
            coverImg: require('../assets/images/GirlOfPopularblogs.png'),
            blogImg: require('../assets/images/PopularBlogsIcon.png'),
            text: ' 7 Natural Hair Dyes: How to Color Your Hair at home',
            MainTitle: 'The Best Hair Styling Tips and Secrets from Professional Salon Stylists',
            Title: '1. Know your hair type',
            Text1:
                'Getting to know your hair can prevent you from wreaking havoc on innocent strands. So, before you pick up a heating tool or brush, learn to distinguish your hair type. Hair typically falls under two categories: Fine and thick.',
            Text2:
                'Your hair is fine if a single strand is hard to see; you struggle with maintaining volume; and locks never feel heavy. You have fewer strands, which are super skinny.',
            subImg: require('../assets/images/BlogInternalImage.png'),
            Text3:
                'Your hair is thick if it feels coarser; bobby pins can’t hold styles in place; and your biggest problem is taming frizz. You seem to have an infinite amount of strands and they weigh a ton.',
        },
        {
            id: 2,
            name: 'Javed Habib',
            dollar: '-$420.00',
            nameshop: '21 Best Hand Creams to Save Your Dry, Cracked Skin',
            date: 'Apr 14.02:30 pm ',
            day: '15 days ago ',
            info: 'debit Whether you want to look younger or embrace your age, these haircuts will make you....',
            image: [
                'https://source.unsplash.com/1024x768/?nature',
                'https://source.unsplash.com/1024x768/?water',
                'https://source.unsplash.com/1024x768/?girl',
                'https://source.unsplash.com/1024x768/?tree',
            ],
            coverImg: require('../assets/images/GirlOfPopularblogs.png'),
            blogImg: require('../assets/images/PopularBlogsIcon.png'),
            MainTitle: 'The Best Hair Styling Tips and Secrets from Professional Salon Stylists',
            text: ' 7 Natural Hair Dyes: How to Color Your Hair at home',
            Title: '1. Know your hair type',
            Text1:
                'Getting to know your hair can prevent you from wreaking havoc on innocent strands. So, before you pick up a heating tool or brush, learn to distinguish your hair type. Hair typically falls under two categories: Fine and thick.',
            Text2:
                'Your hair is fine if a single strand is hard to see; you struggle with maintaining volume; and locks never feel heavy. You have fewer strands, which are super skinny.',
            subImg: require('../assets/images/BlogInternalImage.png'),
            Text3:
                'Your hair is thick if it feels coarser; bobby pins can’t hold styles in place; and your biggest problem is taming frizz. You seem to have an infinite amount of strands and they weigh a ton.',
        },
        {
            id: 3,
            name: 'Javed Habib',
            dollar: '-$220.00',
            nameshop: '21 Best Hand Creams to Save Your Dry, Cracked Skin',
            date: 'Apr 14.02:30 pm ',
            day: '15 days ago ',
            info: 'debit Whether you want to look younger or embrace your age, these haircuts will make you....',
            image: [
                'https://source.unsplash.com/1024x768/?nature',
                'https://source.unsplash.com/1024x768/?water',
                'https://source.unsplash.com/1024x768/?girl',
                'https://source.unsplash.com/1024x768/?tree',
            ],
            coverImg: require('../assets/images/GirlOfPopularblogs.png'),
            blogImg: require('../assets/images/PopularBlogsIcon.png'),
            MainTitle: 'The Best Hair Styling Tips and Secrets from Professional Salon Stylists',
            text: ' 7 Natural Hair Dyes: How to Color Your Hair at home',
            Title: '1. Know your hair type',
            Text1:
                'Getting to know your hair can prevent you from wreaking havoc on innocent strands. So, before you pick up a heating tool or brush, learn to distinguish your hair type. Hair typically falls under two categories: Fine and thick.',
            Text2:
                'Your hair is fine if a single strand is hard to see; you struggle with maintaining volume; and locks never feel heavy. You have fewer strands, which are super skinny.',
            subImg: require('../assets/images/BlogInternalImage.png'),
            Text3:
                'Your hair is thick if it feels coarser; bobby pins can’t hold styles in place; and your biggest problem is taming frizz. You seem to have an infinite amount of strands and they weigh a ton.',
        },

    ],
    latestBlogData: [
        {
            id: 1,
            title: '21 Best Hand Creams to Save Your Dry, Cracked Skin',
            subtitle: 'Whether you want to look younger or embrace your age, these haircuts will make you....',
        },
        {
            id: 1,
            title: '21 Best Hand Creams to Save Your Dry, Cracked Skin',
            subtitle: 'Whether you want to look younger or embrace your age, these haircuts will make you....',
        },
        {
            id: 1,
            title: '21 Best Hand Creams to Save Your Dry, Cracked Skin',
            subtitle: 'Whether you want to look younger or embrace your age, these haircuts will make you....',
        },
    ],
    appointmentData: [
        {
            id: 'u1',
            salonName: 'Mane Beautilocks',
            salonAddress: '2/250 Cambridge St, Wembley WA 6014, Australia',
            apointmentDate: 'Fri,12 Jun',
            apointmentTime: '2Pm- 3Pm',
            alocateTime: '60 min',
            serviceTitle: 'Total Services',
            serviceCount: '2',
            image: [
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
            ],
        },
        {
            id: 'u2',
            salonName: 'Mane Beautilocks',
            salonAddress: '3/250 Cambridge St, Wembley, Australia',
            apointmentDate: 'Wed,10 Jun',
            apointmentTime: '3Pm- 4Pm',
            alocateTime: '20 min',
            serviceTitle: 'Total Services',
            serviceCount: '4',
            image: [
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
            ],
        },
        {
            id: 'u3',
            salonName: 'Mane Beautilocks',
            salonAddress: '3/250 Cambridge St, Wembley, Australia',
            apointmentDate: 'Wed,12 Jun',
            apointmentTime: '5Pm- 6Pm',
            alocateTime: '50 min',
            serviceTitle: 'Total Services',
            serviceCount: '3',
            image: [
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
                require('../assets/images/UpcomingImage.png'),
            ],
        },
    ],
    serviceData: [
        {
            id: 1,
            serviceName: 'Men’s Fancy Hair Cut',
            time: '20 Min',
            price: '$20',
        },
        {
            id: 1,
            serviceName: 'Hair Spa',
            time: '20 Min',
            price: '$50.08',
        },
        {
            id: 1,
            serviceName: 'Oil Treatment',
            time: '20 Min',
            price: '$30.08',
        },
    ],
    transcationData: [
        {
            id: 1,
            date: 'Apr 14 . 02:30pm',
            name: 'Mane Beautilocks',
            transcL: '-$120.00',
        },
        {
            id: 1,
            date: 'Mar 12 . 01:30pm',
            name: 'Cappiello Salon',
            transcL: '-$160.00',
        },
        {
            id: 1,
            date: 'Feb 8 . 11:30am',
            name: 'Bombshell Studio',
            transcL: '-$100.00',
        },
        {
            id: 1,
            date: 'Jan 5 . 10:40am',
            name: 'Sweet Pixie Salon',
            transcL: '-$110.00',
        }
    ],
    favData: [
        {
            name: "Mane Beautilocks",
            address: '2/250 Cambridge St, Wembley WA 6014, Australia',
            ratingText: '3.0',
            desti: "1.4 mi",
            image: require('../assets/images/p4.png')
        },
        {
            name: "Cappiello Salon",
            address: '2/250 Cambridge St, Wembley WA 6014, Australia',
            ratingText: '4.9',
            desti: "1.3 mi",
            image: require('../assets/images/p1.png')
        },
        {
            name: "Bombshell Studio",
            address: '2/250 Cambridge St, Wembley WA 6014, Australia',
            ratingText: '4.0',
            desti: "1.6 mi",
            image: require('../assets/images/p2.png')
        },
        {
            name: "Sweet Pixie Salon",
            address: '2/250 Cambridge St, Wembley WA 6014, Australia',
            ratingText: '2.5',
            desti: "2.0 mi",
            image: require('../assets/images/p3.png')
        },

    ],
    icon: [
        {
            id: 1,
            iconName: 'Call',
            iconImg: require('../assets/images/Call.png')
        },
        {
            id: 2,
            iconName: 'Save',
            iconImg: require('../assets/images/Heart.png')
        },
        {
            id: 3,
            iconName: 'Share',
            iconImg: require('../assets/images/Share.png')
        },
        {
            id: 4,
            iconName: 'Direction',
            iconImg: require('../assets/images/Location.png')
        },
    ],
    reviewData: [
        {
            id: 0,
            image: require('../assets/images/ri1.png'),
            name: ' Joan perkins',

            stars: require('../assets/images/Star.png'),
            rating: '3.0',
            date: '15 days ago',
            Detail:
                'A customer review is a review of a product or service made by a customer who has purchased and used, or had experience with, the product or service.',
        },
        {
            id: 1,
            image: require('../assets/images/ri2.png'),
            name: ' Theresa Webb',
            stars: require('../assets/images/Star.png'),
            rating: '3.0',
            date: '15 days ago',
            Detail:
                'A customer review is a review of a product or service made by a customer who has purchased and used, or had experience with, the product or service.',
        },
    ],
    SocialData: [
        {
            id: 1,
            icon: require('../assets/images/e.png')
        },
        {
            id: 2,
            icon: require('../assets/images/tw.png'),
        },
        {
            id: 3,
            icon: require('../assets/images/fb.png'),
        },
        {
            id: 4,
            icon: require('../assets/images/ig.png'),
        },
        {
            id: 5,
            icon: require('../assets/images/pint.png')
        },
    ],
    sliderImage: [
        require('../assets/images/UpcomingImage.png'),
        require('../assets/images/UpcomingImage.png'),
        require('../assets/images/UpcomingImage.png'),
        require('../assets/images/UpcomingImage.png'),
    ],
    Emojis: [
        {
            Image: require('../assets/images/Emoji-1.png'),
            GreyImage: require('../assets/images/GreyEmoji-1.png'),
        },
        {
            Image: require('../assets/images/Emoji-2.png'),
            GreyImage: require('../assets/images/GreyEmoji-2.png'),
        },
        {
            Image: require('../assets/images/Emoji-3.png'),
            GreyImage: require('../assets/images/GreyEmoji-3.png'),
        },
        {
            Image: require('../assets/images/Emoji-4.png'),
            GreyImage: require('../assets/images/GreyEmoji-4.png'),
        },
        {
            Image: require('../assets/images/Emoji-5.png'),
            GreyImage: require('../assets/images/GreyEmoji-1.png'),
        },
    ],
    Stars: [
        { Image: require('../assets/images/Stars.png'), rating: 2 },
        { Image: require('../assets/images/Stars.png'), rating: 4 },
        { Image: require('../assets/images/Stars.png'), rating: 1 },
        { Image: require('../assets/images/Stars.png'), rating: 5 },
        { Image: require('../assets/images/Stars.png'), rating: 3 },
    ],
    Buttons: [
        { text: 'POOR_SERVICE' },
        { text: 'WRONG_ROUTE' },
        { text: 'TIME_ISSUE' },
        { text: 'BAD_BEHAV' },
    ],
    calenderData: [
        { no: '9', name: 'Mon' },
        { no: '10', name: 'Tue' },
        { no: '11', name: 'Wed' },
        { no: '12', name: 'Thu' },
        { no: '13', name: 'Fri' },
        { no: '14', name: 'Sat' },
    ],
    dateData: [
        { time: '10:00 AM' },
        { time: '10:15 AM' },
        { time: '10:30 AM' },
        { time: '10:45 AM' },
        { time: '11:00 AM' },
        { time: '11:15 AM' },
        { time: '11:30 AM' },
        { time: '11:45 AM' },
        { time: '12:00 PM' },
        { time: '12:15 PM' },
        { time: '12:30 PM' },
        { time: '12:45 PM' },
        { time: '01:00 PM' },
        { time: '01:15 PM' },
        { time: '01:30 PM' },
        { time: '01:45 PM' },
    ],
    CONTENT: [
        {
            isExpanded: false,
            category_name: 'Hair cut',
            subcategory: [
                { val: 'Short', sub: '20 min', price: '$30' },
                { val: 'Medium', sub: '15 min', price: '$25' },
                { val: 'Tuner', sub: '35 min', price: '$35' },
                { val: 'Special', sub: '40 min', price: '$40' },
            ],
        },
        {
            isExpanded: false,
            category_name: 'Beard',
            subcategory: [
                { val: 'Short', sub: '20 min', price: '$30' },
                { val: 'Medium', sub: '15 min', price: '$25' },
                { val: 'Tuner', sub: '35 min', price: '$35' },
                { val: 'Special', sub: '40 min', price: '$40' },
            ],
        },
        {
            isExpanded: false,
            category_name: 'Facials',
            subcategory: [
                { val: 'Short', sub: '20 min', price: '$30' },
                { val: 'Medium', sub: '15 min', price: '$25' },
                { val: 'Tuner', sub: '35 min', price: '$35' },
                { val: 'Special', sub: '40 min', price: '$40' },
            ],
        },
        {
            isExpanded: false,
            category_name: 'Hair color',
            subcategory: [
                { val: 'Short', sub: '20 min', price: '$30' },
                { val: 'Medium', sub: '15 min', price: '$25' },
                { val: 'Tuner', sub: '35 min', price: '$35' },
                { val: 'Special', sub: '40 min', price: '$40' },
            ],
        },
        {
            isExpanded: false,
            category_name: 'Manicure',
            subcategory: [
                { val: 'Short', sub: '20 min', price: '$30' },
                { val: 'Medium', sub: '15 min', price: '$25' },
                { val: 'Tuner', sub: '35 min', price: '$35' },
                { val: 'Special', sub: '40 min', price: '$40' },
            ],
        },
        {
            isExpanded: false,
            category_name: 'Pedicure',
            subcategory: [
                { val: 'Short', sub: '20 min', price: '$30' },
                { val: 'Medium', sub: '15 min', price: '$25' },
                { val: 'Tuner', sub: '35 min', price: '$35' },
                { val: 'Special', sub: '40 min', price: '$40' },
            ],
        },
        {
            isExpanded: false,
            category_name: 'Waxing',
            subcategory: [
                { val: 'Short', sub: '20 min', price: '$30' },
                { val: 'Medium', sub: '15 min', price: '$25' },
                { val: 'Tuner', sub: '35 min', price: '$35' },
                { val: 'Special', sub: '40 min', price: '$40' },
            ],
        },
        {
            isExpanded: false,
            category_name: 'Threading',
            subcategory: [
                { val: 'Short', sub: '20 min', price: '$30' },
                { val: 'Medium', sub: '15 min', price: '$25' },
                { val: 'Tuner', sub: '35 min', price: '$35' },
                { val: 'Special', sub: '40 min', price: '$40' },
            ],
        },
        {
            isExpanded: false,
            category_name: 'Massage',
            subcategory: [
                { val: 'Short', sub: '20 min', price: '$30' },
                { val: 'Medium', sub: '15 min', price: '$25' },
                { val: 'Tuner', sub: '35 min', price: '$35' },
                { val: 'Special', sub: '40 min', price: '$40' },
            ],
        },
    ],

    timeData: [
        { name: 'Monday', time: '10:00 am - 10:00 pm' },
        { name: 'Tuesday', time: '10:00 am - 10:00 pm' },
        { name: 'Wednesday', time: '10:00 am - 10:00 pm' },
        { name: 'Thursday', time: '10:00 am - 10:00 pm' },
        { name: 'Friday', time: '10:00 am - 10:00 pm' },
        { name: 'Saturday', time: '10:00 am - 10:00 pm' },
        { name: 'Sunday', time: '10:00 am - 10:00 pm' },
    ],
    NotificationData: [
        {
            image: require('../assets/images/HomeNotificationTrue.png'),
            title: ('Appointment Booked'),
            text: ('How to choose the right customer for your photo business?'),
            time: '5m ago',
        },
        {
            image: require('../assets/images/HomeNotificationFalse.png'),
            title: ('Appointment Cancelled'),
            text: ('How to choose the right customer for your photo business?'),
            time: '15m ago',
        },
        {
            image: require('../assets/images/HomeNotificationBoth.png'),
            title: ('Appointment Reschedule'),
            text: ('How to choose the right customer for your photo business?'),
            time: '15m ago',
        },
    ],
    salonType: [('Unisex'), ('Men'), ('Women')],
    salonServices: [
        { text: ('Hair Cuts') },
        { text: ('Shaving') },
        { text: ('Foot Care') },
        { text: ('Waxing') },
        { text: ('Eye Care') },
        { text: ('Make-Up') },
        { text: ('Hair Spa') },
        { text: ('Coloring') },
        { text: ('Nail care') },
    ],
    Ratings: [
        { text: ('Any'), icon: false },
        { text: '3.5', icon: true },
        { text: '4.0', icon: true },
        { text: '4.5', icon: true },
    ],
    Availability: [
        { text: ('Any') },
        { text: ('Open now') },
        { text: ('Closed') },
    ],
    Distance: [
        { text: ('Any') },
        { text: '1.0 mi' },
        { text: '3.0 mi' },
        { text: '3.0 mi' },
    ],
    cardData: [
        {
            id: 0,
            number: '1234 5678 1234 9090',
            name: 'Dj ASnderson',
            date: '23/08',
            card: 'Visa',
        },
        {
            id: 0,
            number: '1234 5678 1234 9090',
            name: 'Dj Jhonson',
            date: '23/08',
            card: 'debit',
        },
        {
            id: 0,
            number: '1234 5678 1234 9090',
            name: 'Dj ASnderson',
            date: '23/08',
            card: 'debit',
        },
        {
            id: 0,
            number: '1234 5678 1234 9090',
            name: 'Dj Jhonson',
            date: '23/08',
            card: 'debit',
        },
        {
            id: 0,
            number: '1234 5678 1234 9090',
            name: 'Dj Jhonson',
            date: '23/08',
            card: 'debit',
        },
    ],
    blankdata: [
        require('../assets/images/bar.jpg'),
        require('../assets/images/bar1.jpg'),
        require('../assets/images/bar2.jpg'),
        require('../assets/images/bar3.jpg'),
        require('../assets/images/bar4.jpg'),
        require('../assets/images/bar5.jpg'),
    ],
    videoData: [
        require('../assets/images/photo.png'),
        require('../assets/images/photo.png'),
        require('../assets/images/photo.png'),
        require('../assets/images/photo.png'),
        require('../assets/images/photo.png'),
        require('../assets/images/photo.png'),
    ],
    internalData: [
        { name: 'SERVICES' },
        { name: 'REVIEWS' },
        { name: 'PHOTOS' },
        { name: 'ABOUT' },
    ],
    settingData: [
        {
            id: 0,
            name: 'NOTI',
            info: 'EDIT_PERSONAL',
        },
        {
            id: 1,
            name: 'CHANGE_LAN',
            info: 'EDIT_PAY_METHOD',
        },
        {
            id: 2,
            name: 'CHANGE_PWD',
            info: 'VIEW_ALL_FAV',
        },
        {
            id: 3,
            name: 'TERMS',
            info: 'MANAGE_LAN',
        },
        {
            id: 4,
            name: 'PRIVACY',
            info: 'MANAGE_LAN',
        },
        {
            id: 5,
            name: 'FAQ',
            info: 'MANAGE_LAN',
        },
    ],
    onBoardingData: [
        { name: "GET", sub: 'ORDER' },
        { name: 'BOOK', sub: 'ORDER' },
        { name: '200+', sub: 'ORDER' },
    ],
    settingData1: [
        {
            id: 0,
            name: 'PERSONAL_INFO',
            info: 'EDIT_PERSONAL',
        },
        { id: 1, name: 'PAYMENT_METHOD', info: 'EDIT_PAY_METHOD' },
        { id: 2, name: 'TRANSC_LIST', info: 'MANAGE_PWD' },
        { id: 3, name: 'FAV_SALON', info: 'VIEW_ALL_FAV' },
        { id: 4, name: 'SETTING', info: 'MANAGE_LAN' },
        { id: 5, name: 'REFER', info: 'MANAGE_LAN' },
    ],

}





